# Generated by Django 4.0.6 on 2023-04-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('mini_description', models.CharField(max_length=200)),
                ('full_description', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
                ('gluten_free', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
