# Generated by Django 4.0.6 on 2023-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_special',
            field=models.BooleanField(default=False),
        ),
    ]
